services:
  - type: web
    name: rasa-server
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5005
    dockerCommand: rasa run --enable-api --cors "*" --port 5005
